development: &default
  adapter: postgresql
  database: intelligence_web_development
  encoding: utf8
  min_messages: warning
  pool: 20
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: intelligence_web_test
